name: X-frame-options Configuration
description: "Add x-frame-options header"
# core: 8.x
type: module

# Information added by Drupal.org packaging script on 2018-11-12
version: '8.x-1.1'
core: '8.x'
project: 'x_frame_options'
datestamp: 1542061084
